jobs:
  test-container-deploy:
    include: cider-ci/task-components/container-deploy.yml

    name: Test Deploy to Container

    run_when:
      always:
        type: branch
        include_match: ^.*$
        exclude_match: '^.*no-ci.*$'

    context:

      task_defaults:
        traits: { lxd-on-zfs: yes }

      tasks:
        debian-stretch:
          name: Debian 9 (stretch)
          include: cider-ci/task-components/container-deploy/task-debian.yml

        ubuntu-1604:
          name: Ubuntu 16.04 LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-1604.yml

        ubuntu-1804:
          name: Ubuntu 18.04 LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-1804.yml
